[OCR]
base_height=${OCR_BASE_HEIGHT}
item_width=${OCR_ICON_WIDTH}
item_height=${OCR_ICON_HEIGHT}
item_spacing_height=${OCR_ITEM_SPACING_HEIGHT}
item_spacing_width=${OCR_ITEM_SPACING_WIDTH}
text_recognition_scale=${OCR_TEXT_RECOGNITION_SCALE}

[LOGGING]
level=${LOGGING_LOG_LEVEL@INFO}
loggers=${LOGGING_LOGGERS}
format=${LOGGING_LOG_FORMAT@[%(asctime)s] %(levelname)s [%(name)s] %(message)s}
date_format=${LOGGING_LOG_DATE_FORMAT@%Y-%m-%d %H:%M:%S}
file=${LOGGING_LOG_TO_FILE@0}

[BACKEND]
url=${BACKEND_URL}

[MODELS]
icons_path=${ICONS_PATH@models/icons_model}
quantities_path=${QUANTITIES_PATH@models/quantities_model}
catalog_items_path=${CATALOG_ITEMS_PATH@models/catalog_items.json}

[DEVELOPER]
detect_quantities=${DEVEL_QUANTITIES@1}
detect_icons=${DEVEL_ICONS@1}
detect_stockpile_type=${DEVEL_STOCKPILE_TYPE@1}
detect_stockpile_name=${DEVEL_STOCKPILE_NAME@1}
draw_rectangles=${DEVEL_DRAW_RECTANGLES@0}
save_image=${DEVEL_SAVE_IMAGE@0}
save_stockpile=${DEVEL_SAVE_STOCKPILE@0}
save_name=${DEVEL_SAVE_NAME@0}
save_type=${DEVEL_SAVE_TYPE@0}
backup_path=${DEVEL_BACKUP_PATH@screenshots}

[STOCKPILE_TYPES]
encampment=${STOCKPILE_TYPE_ENCAMPMENT@["Encampment", "Campement", "Feldlager", "Acampamento", "Лагерь", "营地"]}
keep=${STOCKPILE_TYPE_KEEP@["Keep", "Place Forte", "Wehrturm", "Torreão", "Крепость", "要塞"]}
safe_house=${STOCKPILE_TYPE_SAFE_HOUSE@["Safe House", "Planque", "Unterschlupf", "Casa Fortificada", "Yбeжищe", "安全屋"]}
relic_base=${STOCKPILE_TYPE_RELIC_BASE@["Relic Base", "Base Relique", "Reliktbasis", "Base Relíquia", "Peликтoвая база", "遗迹基地"]}
# Portuguese and Russian have different values for bunker levels
bunker_base=${STOCKPILE_TYPE_BUNKER_BASE@["Bunker Base", "Base Bunker", "Bunkerbasis", "Centro do Bunker", "Base de Bunker", "Base de Casamata", "Бункерная база", "Бункерная База", "地堡基地"]}
border_base=${STOCKPILE_TYPE_BORDER_BASE@["Border Base", "Base Frontalière", "Grenzbasis", "Base Fronteiriça", "Пограничная База", "边境基地"]}
town_base=${STOCKPILE_TYPE_TOWN_BASE@["Town Base", "Quartier Général", "Stadtkernbasis", "Base de Cidade", "Ратуша", "城镇基地"]}
bms_longhook=${STOCKPILE_TYPE_BMS_LONGHOOK@["BMS - Longhook"]}
storage_depot=${STOCKPILE_TYPE_STORAGE_DEPOT@["Storage Depot", "Dépôt", "Lagerdepot", "Depósito", "Складское Помещение", "仓库"]}
seaport=${STOCKPILE_TYPE_SEAPORT@["Seaport", "Port", "Seehafen", "Porto", "Морской порт", "海港"]}
undefined=${STOCKPILE_TYPE_UNDEFINED@["Undefined"]}
