version: '3.4'

services:
  foxhole_stockpiles:
    build:
      context: .
    image: foxhole_stockpiles:latest
    container_name: foxhole_stockpiles
    restart: unless-stopped
    ports:
    - 8010:8010
    env_file:
    - .env
    volumes:
    - ./config:/config
